export interface Review {
  author: string;
  rating: number;
  date: string;
  content: string;
}

export interface Accommodation {
  id: string;
  name: string;
  location: string;
  region: string;
  type: string;
  emoji: string;
  secondaryEmoji: string;
  gradient: string;
  subGradient: string;
  price: number;
  rating: number;
  reviewCount: number;
  maxGuests: number;
  beds: number;
  baths: number;
  amenities: string[];
  description: string;
  host: {
    name: string;
    joinYear: number;
    responseRate: number;
    isSuperhost: boolean;
  };
  tag: string;
  category: string;
  workFriendly: string[];
  reviews: Review[];
}

export const accommodations: Accommodation[] = [
  {
    id: "1",
    name: "해운대 오션뷰 하이 스위트",
    location: "부산 해운대구",
    region: "부산",
    type: "아파트먼트",
    emoji: "🌊",
    secondaryEmoji: "🏖️",
    gradient: "from-blue-400 to-cyan-500",
    subGradient: "from-blue-300 to-sky-400",
    price: 180000,
    rating: 4.9,
    reviewCount: 128,
    maxGuests: 4,
    beds: 2,
    baths: 1,
    amenities: ["고속 와이파이", "에어컨/난방", "풀옵션 주방", "세탁기", "오션뷰 발코니", "무료 주차", "넷플릭스"],
    description: "해운대 해변이 눈앞에 펼쳐지는 고층 스위트. 낮에는 파도 소리를 들으며 일하고, 저녁엔 석양을 바라보며 하루를 마무리하세요. 500Mbps 광랜과 듀얼 모니터가 구비되어 있어 어떤 업무 환경에도 최적화되어 있습니다.",
    host: { name: "김민준", joinYear: 2020, responseRate: 99, isSuperhost: true },
    tag: "바다뷰",
    category: "바다",
    workFriendly: ["초고속 광랜 500Mbps", "듀얼 모니터 제공", "독립 업무 공간", "27인치 모니터"],
    reviews: [
      { author: "이수진", rating: 5, date: "2025년 4월", content: "뷰가 정말 최고예요! 와이파이도 빠르고 일하기에 완벽했습니다." },
      { author: "박도현", rating: 5, date: "2025년 3월", content: "해운대 바로 앞이라 퇴근 후 바로 해변 산책 가능. 워케이션에 딱입니다." },
      { author: "최지아", rating: 4, date: "2025년 2월", content: "청결하고 쾌적해요. 바다 뷰가 정말 아름다웠습니다." },
    ],
  },
  {
    id: "2",
    name: "광안리 비치프론트 스튜디오",
    location: "부산 수영구",
    region: "부산",
    type: "스튜디오",
    emoji: "🌉",
    secondaryEmoji: "🌃",
    gradient: "from-indigo-500 to-blue-600",
    subGradient: "from-purple-400 to-indigo-500",
    price: 140000,
    rating: 4.8,
    reviewCount: 89,
    maxGuests: 2,
    beds: 1,
    baths: 1,
    amenities: ["기가 와이파이", "에어컨", "주방", "광안대교 야경뷰", "자전거 대여", "넷플릭스"],
    description: "광안대교 야경이 한눈에 들어오는 감성 스튜디오. 낮에는 카페처럼 편안한 분위기에서 업무를, 밤에는 반짝이는 야경과 함께 여유로운 시간을 보내세요.",
    host: { name: "정수아", joinYear: 2021, responseRate: 97, isSuperhost: true },
    tag: "야경뷰",
    category: "바다",
    workFriendly: ["기가 인터넷 1Gbps", "스탠딩 데스크", "에르고노믹 의자"],
    reviews: [
      { author: "한재원", rating: 5, date: "2025년 4월", content: "광안대교 야경이 정말 환상적이었어요. 일하는 내내 기분이 좋았습니다." },
      { author: "윤미나", rating: 5, date: "2025년 3월", content: "깔끔하고 인테리어가 예뻐요. 재방문 의사 100%" },
    ],
  },
  {
    id: "3",
    name: "기장 해송 프라이빗 풀빌라",
    location: "부산 기장군",
    region: "부산",
    type: "풀빌라",
    emoji: "🏊",
    secondaryEmoji: "🌲",
    gradient: "from-teal-400 to-green-500",
    subGradient: "from-cyan-400 to-teal-500",
    price: 380000,
    rating: 4.95,
    reviewCount: 56,
    maxGuests: 6,
    beds: 3,
    baths: 2,
    amenities: ["프라이빗 풀", "바베큐 시설", "고속 와이파이", "에어컨", "풀옵션 주방", "독립 정원", "프로젝터"],
    description: "소나무 숲 사이 프라이빗 풀이 있는 독채 빌라. 팀 워크샵이나 리트릿에 최적화된 공간으로, 자연 속에서 창의력을 극대화하세요. 대형 회의 테이블과 프로젝터도 구비되어 있습니다.",
    host: { name: "이형준", joinYear: 2019, responseRate: 100, isSuperhost: true },
    tag: "풀빌라",
    category: "풀빌라",
    workFriendly: ["대형 회의 테이블 (8인)", "프로젝터 + 화면", "화이트보드", "초고속 인터넷 500Mbps"],
    reviews: [
      { author: "권태양", rating: 5, date: "2025년 4월", content: "팀 워크샵으로 이용했는데 정말 완벽했어요. 풀도 깨끗하고 시설 최고!" },
      { author: "임채은", rating: 5, date: "2025년 2월", content: "겨울에도 따뜻한 실내 풀을 즐길 수 있어 좋았어요." },
    ],
  },
  {
    id: "4",
    name: "속초 설악 마운틴 뷰 하우스",
    location: "강원 속초시",
    region: "강원도",
    type: "독채",
    emoji: "🏔️",
    secondaryEmoji: "🦅",
    gradient: "from-green-500 to-emerald-600",
    subGradient: "from-lime-400 to-green-500",
    price: 135000,
    rating: 4.85,
    reviewCount: 72,
    maxGuests: 4,
    beds: 2,
    baths: 1,
    amenities: ["고속 와이파이", "에어컨/난방", "풀옵션 주방", "설악산 뷰", "트레킹 가이드 제공", "자전거 2대"],
    description: "설악산 절경이 창 너머로 펼쳐지는 힐링 공간. 맑은 공기와 함께 업무 집중력을 높이고 퇴근 후엔 트레킹으로 하루의 스트레스를 날려버리세요.",
    host: { name: "최성호", joinYear: 2020, responseRate: 98, isSuperhost: false },
    tag: "산뷰",
    category: "산",
    workFriendly: ["고속 인터넷 300Mbps", "창가 전용 업무 공간", "독립 서재"],
    reviews: [
      { author: "조은비", rating: 5, date: "2025년 3월", content: "산 공기가 너무 맑아서 집중이 잘 돼요. 설악산 뷰 보며 일하니 힐링됩니다." },
      { author: "신동욱", rating: 4, date: "2025년 1월", content: "겨울 설경이 정말 아름다웠어요. 따뜻하고 편안한 공간이었습니다." },
    ],
  },
  {
    id: "5",
    name: "강릉 경포 오션하우스",
    location: "강원 강릉시",
    region: "강원도",
    type: "하우스",
    emoji: "⛱️",
    secondaryEmoji: "☕",
    gradient: "from-sky-400 to-blue-500",
    subGradient: "from-blue-300 to-cyan-400",
    price: 120000,
    rating: 4.7,
    reviewCount: 94,
    maxGuests: 6,
    beds: 3,
    baths: 2,
    amenities: ["와이파이", "에어컨", "풀옵션 주방", "넓은 마당", "자전거 4대", "경포해변 도보 5분"],
    description: "강릉 커피 거리와 경포 해변이 가까운 넓은 단독 주택. 바리스타 취향의 호스트가 직접 내려주는 핸드드립 커피로 아침을 시작하고, 자전거로 강릉 곳곳을 탐험하세요.",
    host: { name: "박소연", joinYear: 2022, responseRate: 96, isSuperhost: false },
    tag: "해변",
    category: "바다",
    workFriendly: ["와이파이 300Mbps", "넓은 거실 업무공간", "테라스 야외 업무"],
    reviews: [
      { author: "정민아", rating: 5, date: "2025년 4월", content: "자전거 빌려서 해변 달리고 카페 들르고 최고의 워케이션!" },
      { author: "김태한", rating: 4, date: "2025년 3월", content: "숙소가 넓어서 팀원들과 쓰기 좋았어요. 마당도 있어서 좋았습니다." },
    ],
  },
  {
    id: "6",
    name: "제주 협재 오션뷰 독채",
    location: "제주 한림읍",
    region: "제주도",
    type: "독채",
    emoji: "🌺",
    secondaryEmoji: "🐬",
    gradient: "from-orange-400 to-pink-500",
    subGradient: "from-rose-400 to-orange-400",
    price: 220000,
    rating: 4.9,
    reviewCount: 167,
    maxGuests: 4,
    beds: 2,
    baths: 1,
    amenities: ["기가 와이파이", "에어컨/온돌", "풀옵션 주방", "협재해변 도보 3분", "오션뷰 루프탑", "스노클링 장비"],
    description: "에메랄드빛 협재 해변이 3분 거리인 독채. 투명한 바다를 바라보며 업무하고 퇴근 후엔 스노클링을 즐겨보세요. 제주에서 가장 아름다운 노을을 루프탑에서 감상할 수 있습니다.",
    host: { name: "현지우", joinYear: 2019, responseRate: 100, isSuperhost: true },
    tag: "에메랄드해변",
    category: "섬",
    workFriendly: ["기가 인터넷 1Gbps", "루프탑 야외 업무공간", "바다뷰 전용 데스크"],
    reviews: [
      { author: "백서연", rating: 5, date: "2025년 4월", content: "협재 해변 걸어서 3분! 뷰도 아름답고 와이파이도 빠르고 최고입니다." },
      { author: "강준혁", rating: 5, date: "2025년 3월", content: "루프탑에서 일하는데 너무 행복했어요. 제주 워케이션 최강 숙소!" },
      { author: "오하은", rating: 5, date: "2025년 2월", content: "깨끗하고 호스트도 친절해요. 다음에 또 오겠습니다!" },
    ],
  },
  {
    id: "7",
    name: "서귀포 한라산뷰 감귤 농가",
    location: "제주 서귀포시",
    region: "제주도",
    type: "농가형",
    emoji: "🍊",
    secondaryEmoji: "⛰️",
    gradient: "from-amber-400 to-orange-500",
    subGradient: "from-yellow-400 to-amber-500",
    price: 160000,
    rating: 4.8,
    reviewCount: 83,
    maxGuests: 4,
    beds: 2,
    baths: 1,
    amenities: ["와이파이", "에어컨", "주방", "감귤 농장 체험", "한라산 뷰", "독립 정원", "감귤 무제한 제공"],
    description: "제주 감귤 농가를 리모델링한 독특한 공간. 직접 딴 감귤로 만든 주스와 함께 한라산을 바라보며 특별한 워케이션을 경험하세요. 감귤 따기 체험도 포함입니다.",
    host: { name: "고영준", joinYear: 2021, responseRate: 95, isSuperhost: false },
    tag: "감귤농가",
    category: "섬",
    workFriendly: ["와이파이 200Mbps", "정원 야외 업무공간", "한라산뷰 테라스"],
    reviews: [
      { author: "문지원", rating: 5, date: "2025년 3월", content: "감귤 따는 체험까지 할 수 있었어요! 정말 특별한 경험이었습니다." },
      { author: "송민호", rating: 4, date: "2025년 2월", content: "한라산 뷰 보며 일하니 힐링이 됐어요. 시설도 깔끔했습니다." },
    ],
  },
  {
    id: "8",
    name: "제주 함덕 화이트 빌라",
    location: "제주 조천읍",
    region: "제주도",
    type: "빌라",
    emoji: "🏡",
    secondaryEmoji: "🌴",
    gradient: "from-cyan-400 to-blue-500",
    subGradient: "from-sky-300 to-cyan-400",
    price: 195000,
    rating: 4.85,
    reviewCount: 112,
    maxGuests: 6,
    beds: 3,
    baths: 2,
    amenities: ["기가 와이파이", "에어컨", "풀옵션 주방", "함덕해변 도보 1분", "루프탑 테라스", "BBQ 시설"],
    description: "제주에서 가장 맑은 함덕 해변까지 걸어서 1분! 화이트 컬러의 북유럽 감성 공간에서 제주 블루를 감상하세요. 인스타그래머블한 인테리어가 업무 후 여유를 더해줍니다.",
    host: { name: "양채린", joinYear: 2020, responseRate: 99, isSuperhost: true },
    tag: "함덕해변",
    category: "섬",
    workFriendly: ["기가 인터넷 1Gbps", "루프탑 업무공간", "대형 27인치 모니터"],
    reviews: [
      { author: "전하준", rating: 5, date: "2025년 4월", content: "함덕 해변까지 1분이라 아침마다 해변 산책하고 일했어요. 최고의 워케이션!" },
      { author: "홍나연", rating: 5, date: "2025년 3월", content: "인테리어가 너무 예뻐요. 사진도 많이 찍었습니다." },
    ],
  },
  {
    id: "9",
    name: "전주 한옥마을 고택 스테이",
    location: "전북 전주시",
    region: "전주",
    type: "한옥",
    emoji: "🏯",
    secondaryEmoji: "🍵",
    gradient: "from-amber-600 to-yellow-500",
    subGradient: "from-amber-500 to-orange-400",
    price: 130000,
    rating: 4.75,
    reviewCount: 61,
    maxGuests: 4,
    beds: 2,
    baths: 1,
    amenities: ["와이파이", "온돌 난방", "전통 조식 포함", "다도 체험", "한복 대여", "한옥마을 뷰"],
    description: "100년 역사의 한옥을 현대적으로 리노베이션한 공간. 한국의 전통미 속에서 창의적인 작업에 집중하고 싶다면 이곳으로. 매일 아침 한식 조식이 제공됩니다.",
    host: { name: "김선영", joinYear: 2018, responseRate: 97, isSuperhost: true },
    tag: "전통한옥",
    category: "역사",
    workFriendly: ["와이파이 200Mbps", "독립 서재", "전통 목재 업무 책상"],
    reviews: [
      { author: "이지수", rating: 5, date: "2025년 3월", content: "한옥에서 일하는 특별한 경험! 전통 아침식사도 맛있었어요." },
      { author: "박찬영", rating: 4, date: "2025년 2월", content: "분위기 정말 좋아요. 한옥 감성이 업무 집중에 도움이 됐어요." },
    ],
  },
  {
    id: "10",
    name: "경주 대릉원뷰 역사 빌라",
    location: "경북 경주시",
    region: "경주",
    type: "별장",
    emoji: "🏛️",
    secondaryEmoji: "🌸",
    gradient: "from-purple-500 to-indigo-600",
    subGradient: "from-violet-400 to-purple-500",
    price: 145000,
    rating: 4.8,
    reviewCount: 48,
    maxGuests: 4,
    beds: 2,
    baths: 1,
    amenities: ["고속 와이파이", "에어컨/난방", "주방", "대릉원 야경뷰", "자전거 2대", "역사 투어 가이드 제공"],
    description: "천년 고도 경주의 역사 속으로. 낮에는 집중 업무, 퇴근 후엔 첨성대와 대릉원을 산책하며 영감을 얻으세요. 봄에는 벚꽃, 가을에는 단풍이 창밖을 수놓습니다.",
    host: { name: "서준모", joinYear: 2021, responseRate: 96, isSuperhost: false },
    tag: "역사유산",
    category: "역사",
    workFriendly: ["와이파이 300Mbps", "조용한 독립 업무환경", "대형 창가 업무 공간"],
    reviews: [
      { author: "노서현", rating: 5, date: "2025년 2월", content: "경주의 고즈넉한 분위기가 정말 좋았어요. 벚꽃 시즌에 딱이에요!" },
      { author: "유재현", rating: 4, date: "2025년 1월", content: "자전거로 대릉원 돌아보는 게 너무 좋았습니다." },
    ],
  },
  {
    id: "11",
    name: "여수 밤바다 오션뷰 펜션",
    location: "전남 여수시",
    region: "여수",
    type: "펜션",
    emoji: "🚢",
    secondaryEmoji: "🌅",
    gradient: "from-teal-500 to-cyan-600",
    subGradient: "from-emerald-400 to-teal-500",
    price: 165000,
    rating: 4.85,
    reviewCount: 97,
    maxGuests: 4,
    beds: 2,
    baths: 1,
    amenities: ["기가 와이파이", "에어컨", "주방", "오션뷰 테라스", "돌산대교 뷰", "낚시 체험 포함"],
    description: "노래로 유명한 여수 밤바다가 펼쳐지는 프리미엄 뷰 펜션. 여수항의 낭만을 느끼며 업무 효율을 높이세요. 화상회의에 최적화된 조용한 환경을 제공합니다.",
    host: { name: "나경민", joinYear: 2020, responseRate: 98, isSuperhost: true },
    tag: "밤바다뷰",
    category: "바다",
    workFriendly: ["기가 인터넷 1Gbps", "오션뷰 업무공간", "화상회의 최적화 음향"],
    reviews: [
      { author: "배소미", rating: 5, date: "2025년 4월", content: "여수 밤바다 뷰가 실화예요... 저녁에 테라스 나가면 진짜 힐링됩니다." },
      { author: "표준현", rating: 5, date: "2025년 3월", content: "낚시 체험도 너무 재밌었고, 숙소도 깔끔했어요." },
    ],
  },
  {
    id: "12",
    name: "남해 독일마을 힐사이드 빌라",
    location: "경남 남해군",
    region: "남해",
    type: "빌라",
    emoji: "🌿",
    secondaryEmoji: "🏘️",
    gradient: "from-green-400 to-teal-500",
    subGradient: "from-lime-400 to-green-500",
    price: 155000,
    rating: 4.7,
    reviewCount: 44,
    maxGuests: 6,
    beds: 3,
    baths: 2,
    amenities: ["와이파이", "에어컨", "풀옵션 주방", "독일마을 전망", "독립 정원", "BBQ 시설", "바다 조망"],
    description: "남해 독일마을의 이국적인 풍경이 펼쳐지는 힐사이드 빌라. 유럽 감성의 공간에서 바다와 초록 언덕을 바라보며 일하세요. 여럿이 함께하는 워케이션에 딱입니다.",
    host: { name: "하유리", joinYear: 2022, responseRate: 94, isSuperhost: false },
    tag: "이국풍경",
    category: "산",
    workFriendly: ["와이파이 200Mbps", "정원 야외 업무공간", "뷰 테라스"],
    reviews: [
      { author: "공민서", rating: 5, date: "2025년 3월", content: "독일마을 분위기가 너무 특별해요. 이국적인 환경에서 일하니 창의력이 올라갔어요." },
      { author: "장혜진", rating: 4, date: "2025년 2월", content: "정원에서 바베큐하면서 팀 회식도 했어요. 좋은 추억이 됐습니다." },
    ],
  },
];
